### ISSUE TITLE
Feedback on first submission

### ISSUE THREAD

**Issue by Anisha7** [lacunahag/cs-1.3#1]
Good job on submitting your first challenges! Here are some recommendations for improvement:

- Come to office hours for help on base conversions and string algorithms. 
- Your strings code is not in the repo. Did you push it to Github?
- For your binary recursive approach, think about how you can use left and right variables to give the illusion of slicing, but not actually slice the list. This will be more memory efficient and help prevent confusion with tracking your index. Come to office hours, and I can walk you through it :)

I highly recommend coming to office hours and working on challenges in order to catch up.

**Comment by jasminedevv** [comment]
Hi Anisha!

Sorry I totally missed this. I got the base conversions working and the binary search optimization shouldn't be too much trouble but I will need help with the string search algorithms. I'll see you or Ansel at office hours.
