### ISSUE TITLE
Feedback on second submission

### ISSUE THREAD

**Issue by Anisha7** [lacunahag/cs-1.3#2]
Good job on completing the second coding challenge. Here's some feedback on how to improve your code further:
- For your ArrayStack, you should check whether your array is empty before popping from it. Otherwise all of your tests pass :)
- Great job on your sets code! You are so close! Try implementing 3-4 tests per method. Use Alan’s test cases as a reference. Its way harder to implement your functions than to test it —> you are simply calling your functions on different inputs and checking the solution with assert statements. 
- Add some (3-4) images to your article. Its required.

**Comment by jasminedevv** [comment]
Alright all three should be fixed. Let me know if there's anything else.
